epl_team_dict = {'Arsenal': 'Arsenal',
                 'Brighton': 'Brighton & Hove Albion',
                 'Chelsea': 'Chelsea',
                 'Crystal Palace': 'Crystal Palace',
                 'Everton': 'Everton',
                 'Southampton': 'Southampton',
                 'Watford': 'Watford',
                 'West Brom': 'West Bromwich Albion',
                 'Man United': 'Manchester United',
                 'Newcastle': 'Newcastle United',
                 'Bournemouth': 'Bournemouth',
                 'Burnley': 'Burnley',
                 'Leicester': 'Leicester City',
                 'Liverpool': 'Liverpool',
                 'Stoke': 'Stoke City',
                 'Swansea': 'Swansea City',
                 'Huddersfield': 'Huddersfield Town',
                 'Tottenham': 'Tottenham Hotspur',
                 'Man City': 'Manchester City',
                 'West Ham': 'West Ham United'}

bundesliga_team_dict = {'Bayern Munich': 'FC Bayern Munich',
                        'Hamburg': 'Hamburger SV',
                        'Hertha': 'Hertha BSC Berlin',
                        'Hoffenheim': 'TSG 1899 Hoffenheim',
                        'Mainz': '1. FSV Mainz 05',
                        'Schalke 04': 'FC Schalke 04',
                        'Wolfsburg': 'VfL Wolfsburg',
                        'Freiburg': 'SC Freiburg',
                        "M'gladbach": 'Borussia Mönchengladbach',
                        'FC Koln': '1. FC Köln',
                        'Augsburg': 'FC Augsburg',
                        'Dortmund': 'Borussia Dortmund',
                        'Ein Frankfurt': 'Eintracht Frankfurt',
                        'Leverkusen': 'Bayer 04 Leverkusen',
                        'Stuttgart': 'VfB Stuttgart',
                        'Werder Bremen': 'SV Werder Bremen',
                        'Hannover': 'Hannover 96',
                        'RB Leipzig': 'RB Leipzig'}

laliga_team_dict = {'Leganes': 'CD Leganés',
                    'Valencia': 'Valencia CF',
                    'Celta': 'RC Celta de Vigo',
                    'Girona': 'Girona CF',
                    'Sevilla': 'Sevilla FC',
                    'Ath Bilbao': 'Athletic Club de Bilbao',
                    'Barcelona': 'FC Barcelona',
                    'La Coruna': 'RC Deportivo de La Coruña',
                    'Levante': 'Levante UD',
                    'Malaga': 'Málaga CF',
                    'Betis': 'Real Betis Balompié',
                    'Sociedad': 'Real Sociedad',
                    'Alaves': 'Deportivo Alavés',
                    'Las Palmas': 'UD Las Palmas',
                    'Eibar': 'SD Eibar',
                    'Espanol': 'RCD Espanyol',
                    'Getafe': 'Getafe CF',
                    'Real Madrid': 'Real Madrid CF',
                    'Villarreal': 'Villarreal CF',
                    'Ath Madrid': 'Atlético Madrid'
                    }

seriea_teams_dict = {'Juventus': 'Juventus',
                     'Verona': 'Hellas Verona',
                     'Atalanta': 'Atalanta',
                     'Bologna': 'Bologna',
                     'Crotone': 'Crotone',
                     'Inter': 'Inter',
                     'Lazio': 'Lazio',
                     'Sampdoria': 'Sampdoria',
                     'Sassuolo': 'Sassuolo',
                     'Udinese': 'Udinese',
                     'Benevento': 'Benevento Calcio',
                     'Genoa': 'Genoa',
                     'Roma': 'Roma',
                     'Chievo': 'Chievo Verona',
                     'Fiorentina': 'Fiorentina',
                     'Milan': 'Milan',
                     'Napoli': 'Napoli',
                     'Spal': 'Ferrara (SPAL)',
                     'Torino': 'Torino',
                     'Cagliari': 'Cagliari'
                    }
